<?php

declare(strict_types=1);

/*
 * This file is part of SolidWorx Platform project.
 *
 * (c) Pierre du Plessis <open-source@solidworx.co>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace SolidWorx\Platform\Component\Uid;

use Symfony\Component\Uid\Ulid;

/**
 * EmptyUlid is a special case of Ulid that represents an empty value.
 * It is used to represent a non-existent or uninitialized Ulid.
 *
 * It's mostly useful for Doctrine entities that uses Ulid as primary key,
 * and the Ulid is generated by the {@see \Symfony\Bridge\Doctrine\IdGenerator\UlidGenerator} class,
 * then this can be used as a default value for the property.
 */
final class EmptyUlid
{
    private function __construct()
    {
    }

    public static function create(): Ulid
    {
        return new class() extends Ulid {
            public function __construct()
            {
                parent::__construct(self::NIL);
            }
        };
    }
}
